name: Mise à jour du fichier Excel

on:
  schedule:
    - cron: "0 0 * * *"  # Exécute tous les jours à minuit (UTC)
  push:
    branches:
      - main  # Exécute lors d'un push sur la branche principale

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v2

      - name: Configurer Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Exécuter le script de mise à jour
        run: python update_excel.py

      - name: Téléverser le fichier mis à jour
        uses: actions/upload-artifact@v2
        with:
          name: ventes.xlsx
          path: ventes.xlsx
